"""
	Download whatlinkshere pages list (linkujące).
"""

import pywikibot, re
from utils.api import *
from utils.file import *

import logging
logging.basicConfig(filename='logs/list-links.log', encoding='utf-8', level=logging.DEBUG)

site = pywikibot.Site("pl", 'wikipedia')
output_path = './io/lists/'
limit = -1
#limit = 5

## clear dir
#import shutil
#shutil.rmtree(output_path, ignore_errors=True)

# init dir
import os

def download(tpl, base_path, list_name, append = True):
	print('\nTemplate:', tpl)
	logging.info('\n\tTemplate: %s', tpl)

	os.makedirs(base_path, exist_ok=True)

	# download & save
	generator = list_template_embedded(site, tpl, content=False)
	#generator = pywikibot.pagegenerators.RegexFilter.titlefilter(generator, r'^Night of the')
	counter = 0
	errors = 0
	pages = []
	for page in generator:
		counter += 1
		try:
			# print(page.title())
			# logging.debug(page.title())
			pages.append(page.title())
			if limit > 0 and counter > limit:
				break
		except Exception as error:
			errors += 1
			logging.error({'page':page, 'error':error})
	save_list(pages, base_path, list_name, append = append)
	summary = """
	Template: {tpl},
	Pages count: {counter},
	Errors count: {errors}.
	""".format_map({
		'counter': str(counter),
		'errors': str(errors),
		'tpl': tpl,
	})
	print(summary)
	logging.info(summary)
	

#"""
tpls = [
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Armenii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Azerbejdżanu na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Azerbejdżanu na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Azerbejdżanu na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Azerbejdżanu na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Azerbejdżanu na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Azerbejdżanu na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Białorusi na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Białorusi na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Białorusi na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Białorusi na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Białorusi na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Białorusi na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Białorusi na igrzyskach olimpijskich - Tokio 2020",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Bułgarii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Chin na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Chin na igrzyskach olimpijskich - Tokio 2020",
	"Zapaśnicy Czech na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Czech na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Czech na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Berlin 1936",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Czechosłowacji na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Finlandii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Gruzji na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Gruzji na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Gruzji na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Gruzji na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Gruzji na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Gruzji na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Montreal 1976",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Seul 1988",
	"Zapaśnicy Iranu na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Berlin 1936",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Helsinki 1952",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Los Angeles 1932",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Los Angeles 1984",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Meksyk 1968",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Melbourne 1956",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Monachium 1972",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Montreal 1976",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Rzym 1960",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Seul 1988",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Japonii na Igrzyskach Olimpijskich - Tokio 1964",
	"Zapaśnicy Jugosławii (sportowy niezależni) na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Jugosławii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Amsterdam 1928",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Berlin 1936",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Los Angeles 1932",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Los Angeles 1984",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Paryż 1924",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Seul 1988",
	"Zapaśnicy Kanady na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Kanady na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Kazachstanu na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Kazachstanu na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Kazachstanu na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Kazachstanu na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Kazachstanu na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Kazachstanu na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Kirgistanu na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Kirgistanu na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Kirgistanu na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Kirgistanu na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Kirgistanu na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Kirgistanu na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Los Angeles 1984",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Montreal 1976",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Seul 1988",
	"Zapaśnicy Korei Południowej na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Korei Południowej na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Korei Północnej na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Moskwa 1980",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Kuby na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Kuby na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Mołdawii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Mongolii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Niemiec na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy NRD na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy NRD na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy NRD na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy NRD na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy NRD na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy RFN na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy RFN na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy RFN na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy RFN na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy RFN na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Rosji na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Rosji na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Rosji na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Rosji na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Rosji na Igrzyskach Olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Rosji na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Rumunii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Słowacji na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Słowacji na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Słowacji na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Słowacji na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Londyn 2012",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Szwecji na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Amsterdam 1928",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Ateny 2004",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Barcelona 1992",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Berlin 1936",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Helsinki 1952",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Londyn 1948",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Los Angeles 1984",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Meksyk 1968",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Melbourne 1956",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Monachium 1972",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Montreal 1976",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Paryż 1924",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Rzym 1960",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Seul 1988",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Turcji na Igrzyskach Olimpijskich - Tokio 1964",
	"Zapaśnicy Ukrainy na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Ukrainy na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Ukrainy na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Ukrainy na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Ukrainy na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Ukrainy na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Uzbekistanu na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Uzbekistanu na Igrzyskach Olimpijskich - Atlanta 1996",
	"Zapaśnicy Uzbekistanu na Igrzyskach Olimpijskich - Londyn 2012",
	"Zapaśnicy Uzbekistanu na Igrzyskach Olimpijskich - Pekin 2008",
	"Zapaśnicy Uzbekistanu na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Uzbekistanu na Igrzyskach Olimpijskich - Sydney 2000",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Antwerpia 1920",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Berlin 1936",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Londyn 1908",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Los Angeles 1932",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Paryż 1924",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Sztokholm 1912",
	"Zapaśnicy Wielkiej Brytanii na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Amsterdam 1928",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Antwerpia 1920",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Ateny 2004",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Atlanta 1996",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Berlin 1936",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Londyn 1948",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Los Angeles 1932",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Los Angeles 1984",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Paryż 1924",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Pekin 2008",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Rio de Janeiro 2016",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Sydney 2000",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Sztokholm 1912",
	"Zapaśnicy Włoch na igrzyskach olimpijskich - Tokio 1964",
	"Zapaśnicy WNP na igrzyskach olimpijskich - Barcelona 1992",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Helsinki 1952",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Meksyk 1968",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Melbourne 1956",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Monachium 1972",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Montreal 1976",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Moskwa 1980",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Rzym 1960",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Seul 1988",
	"Zapaśnicy ZSRR na igrzyskach olimpijskich - Tokio 1964"
]
#"""
"""
tpls = [
	"Zapaśnicy Węgier na igrzyskach olimpijskich – Amsterdam 1928",
	"Zapaśnicy Węgier na igrzyskach olimpijskich – Atlanta 1996",
	"Zapaśnicy Węgier na igrzyskach olimpijskich – Barcelona 1992",
]
"""
list_name = "zapasnicy.py"

append = False
for page_title in tpls:
	download(page_title, output_path, list_name, append = append)
	append = True

# add pages variable
file = make_safe_filename(list_name)
path = os.path.join(output_path, file)
with open(path, "r+", encoding='utf-8') as text_file:
	text_file.seek(0)
	text = text_file.read()
	text_file.seek(0)
	text_file.write("pages = [\n")
	text_file.write(text)
	text_file.write("\n]\n")
# download(tpls[0], output_path, list_name, append = False)
# download(tpls[1], output_path, list_name)
